# NAME: Vagrantfile
# AUTHOR: Joaquin Menchaca
# UPDATED: 2016-04-27
#
# PURPOSE: Multi-Machine Demo (in-memory structure)
# DEPENDENCIES:
#  * VirtualBox, Vagrant
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_PARSE  = "#{Dir.pwd}/../scriptlib/default.vagrantfile"
VAGRANT_CREATE = "#{Dir.pwd}/../scriptlib/common.vagrantfile"

############### BUILD DATASTRUCTURE
if File.file?("#{VAGRANT_PARSE}")
   eval File.read("#{VAGRANT_PARSE}")
end

############### CONFIGURE VAGRANT MACHINES
if File.file?("#{VAGRANT_CREATE}")
   eval File.read("#{VAGRANT_CREATE}")
end
