# NAME: Vagrantfile
# AUTHOR: Joaquin Menchaca
# UPDATED: 2016-04-27
#
# PURPOSE: Multi-Machine Demo (in-memory structure)
# DEPENDENCIES:
#  * VirtualBox, Vagrant
#
# -*- mode: ruby -*-
# vi: set ft=ruby :
############### GET CURRENT TIME
time = Time.now.strftime("%Y%m%d%H%M%S")

settings = {
    "hosts" => {
        "client" => "192.168.53.83",
        "master" => "192.168.53.84",
        "slave1" => "192.168.53.85",
        "slave2" => "192.168.53.86"
    },
    "ports" => {
        "master" => [{
            "guest" => 80,
            "host" => 8080
        }, {
            "guest" => 3306,
            "host" => 13306
        }]
    },
    "defaults" => {
        "master" => true
    }
}
############### CONFIGURE VAGRANT MACHINES
Vagrant.configure("2") do |config|
  settings['hosts'].each do |hostname, ipaddr|
    default = settings['defaults'][hostname] || false
    config.vm.define hostname, primary: default  do |node|
      node.vm.box = "ubuntu/trusty64"
      node.vm.hostname = "#{hostname}"
      node.vm.network "private_network", ip: ipaddr
      node.vm.provider("virtualbox") { |vbox| vbox.name = "#{hostname}_#{time}" }
      if settings['ports'][hostname]
        settings['ports'][hostname].each do |forward|
          node.vm.network "forwarded_port", guest: forward['guest'], host: forward['host']
        end
      end
      # Provision
      node.vm.provision "shell", path: "scripts/#{hostname}.sh"
    end
  end
end
