# NAME: Vagrantfile
# AUTHOR: Joaquin Menchaca
# UPDATED: 2016-04-25
#
# PURPOSE: Multi-Machine Demo w/ Dynamic Config from settings in INI config.
# DEPENDENCIES:
#  * VirtualBox, Vagrant
#  * 'inifile' gem installed into Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

############### CONSTANTS
CONFIGFILE="./config/global.ini"
############### GET CURRENT TIME
time = Time.now.strftime("%Y%m%d%H%M%S")
############### BUILD RUBY DATA STRUCTURE (HoHoLoH)
require 'inifile'
settings = IniFile.load(CONFIGFILE)
# Build Ruby structure (HoHoLoH) from INI data structure (HoH)
# Key=Value String format is 'hostname="guest:host,guest:host"'
settings['ports'].each  do |hostname,forwards|
  settings['ports'][hostname] = []
  forwards.split(/,/).each do |forward|
    guest, host = forward.split(/:/)
    settings['ports'][hostname] << {'guest'=>guest, 'host'=>host}
  end
end

############### CONFIGURE VAGRANT MACHINES
Vagrant.configure("2") do |config|
  settings['hosts'].each do |hostname, ipaddr|
    default = settings['defaults'][hostname] || false
    config.vm.define hostname, primary: default  do |node|
      node.vm.box = "ubuntu/trusty64"
      node.vm.hostname = "#{hostname}"
      node.vm.network "private_network", ip: ipaddr
      node.vm.provider("virtualbox") { |vbox| vbox.name = "#{hostname}_#{time}" }
      if settings['ports'][hostname]
        settings['ports'][hostname].each do |forward|
          node.vm.network "forwarded_port", guest: forward['guest'], host: forward['host']
        end
      end
      # Provision
      node.vm.provision "shell", path: "scripts/setup-all.sh"
      node.vm.provision "shell", path: "scripts/#{hostname}.sh"
    end
  end
end
