# NAME: Vagrantfile
# AUTHOR: Joaquin Menchaca
# UPDATED: 2016-04-25
#
# PURPOSE: Multi-Machine Demo w/ Dynamic Config from settings in INI config.
# DEPENDENCIES:
#  * VirtualBox, Vagrant
#  * 'inifile' gem installed into Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

############### CONSTANTS
CONFIGFILE     = ENV['VAGRANT_CONFIG'] || './config/global.ini'
CONFIGTYPE     = CONFIGFILE.split(/\./)[-1]
VAGRANT_PARSE  = "#{Dir.pwd}/../scriptlib/#{CONFIGTYPE}.rb"
VAGRANT_CREATE = "#{Dir.pwd}/../scriptlib/common.vagrantfile"
BASE_LIBRARY   = "#{Dir.pwd}/../scriptlib/baselib.sh"
LOCAL_LIBRARY  = "#{Dir.pwd}/scripts/baselib.src"

############## COPY LOCAL LIBRARY
FileUtils.cp(BASE_LIBRARY, LOCAL_LIBRARY, :preserve => false)

############### BUILD DATASTRUCTURE
if File.file?("#{VAGRANT_PARSE}")
   eval File.read("#{VAGRANT_PARSE}")
end

############### CONFIGURE VAGRANT MACHINES
if File.file?("#{VAGRANT_CREATE}")
   eval File.read("#{VAGRANT_CREATE}")
end
