---
  hosts:
    client: "192.168.53.43"
    master: "192.168.53.44"
    slave1: "192.168.53.45"
    slave2: "192.168.53.46"
  ports:
    master:
      -
        guest: 80
        host: 8088
      -
        guest: 3306
        host: 13306
  defaults:
    master: true
