# NAME: Vagrantfile
# AUTHOR: Joaquin Menchaca
# UPDATED: 2016-04-25
#
# PURPOSE: Multi-Machine Demo (static)
# DEPENDENCIES:
#  * VirtualBox, Vagrant
#
# -*- mode: ruby -*-
# vi: set ft=ruby :
############### GET CURRENT TIME
@time = Time.now.strftime("%Y%m%d%H%M%S")

############### CONFIGURE VAGRANT MACHINES
Vagrant.configure("2") do |config|
  config.vm.define "client" do |client|
    client.vm.box = "ubuntu/trusty64"
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.53.73"
    client.vm.provider("virtualbox") { |vbox| vbox.name = "client_#{@time}" }
    client.vm.provision "shell", path: "scripts/client.sh"
  end

  config.vm.define "master", primary: true do |master|
    master.vm.box = "ubuntu/trusty64"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.53.74"
    master.vm.provider("virtualbox") { |vbox| vbox.name = "master_#{@time}" }
    master.vm.network "forwarded_port", guest: 80, host: 8080
    master.vm.network "forwarded_port", guest: 3306, host: 13306
    master.vm.provision "shell", path: "scripts/master.sh"
  end

  config.vm.define "slave1" do |slave1|
    slave1.vm.box = "ubuntu/trusty64"
    slave1.vm.hostname = "slave1"
    slave1.vm.network "private_network", ip: "192.168.53.75"
    slave1.vm.provider("virtualbox") { |vbox| vbox.name = "slave1_#{@time}" }
    slave1.vm.provision "shell", path: "scripts/slave1.sh"
  end

  config.vm.define "slave2" do |slave2|
    slave2.vm.box = "ubuntu/trusty64"
    slave2.vm.hostname = "slave2"
    slave2.vm.network "private_network", ip: "192.168.53.76"
    slave2.vm.provider("virtualbox") { |vbox| vbox.name = "slave2_#{@time}" }
    slave2.vm.provision "shell", path: "scripts/slave2.sh"
  end
end
