# -*- mode: ruby -*-
# vi: set ft=ruby :

time = Time.now.strftime("%Y%m%d%H%M%S")

# Parse YAML File into Ruby hash
require 'yaml'
nodes = YAML.load(File.read("config/global.yaml"))['hosts']

Vagrant.configure("2") do |config|
  nodes.each do |nodename, ipaddr|
    config.vm.define nodename do |node|
      node.vm.box = "ubuntu/trusty64"
      node.vm.hostname = "#{nodename}"
      node.vm.network "private_network", ip: ipaddr
      node.vm.provider("virtualbox") { |vbox| vbox.name = "#{nodename}_#{time}" }

      # Provision
      #node.vm.provision "shell", path: "scripts/setup-all.sh"
      node.vm.provision "shell", path: "scripts/#{nodename}.sh"
    end
  end
end
