# -*- mode: ruby -*-
# vi: set ft=ruby :

time = Time.now.strftime("%Y%m%d%H%M%S")

# Parse Hosts File into Ruby hash
nodes = Hash.new
File.readlines('config/global.hosts').map(&:chomp).each do |line|
  ipaddr, nodename = line.split(" ")
  nodes[nodename] = ipaddr
end

Vagrant.configure("2") do |config|
  nodes.each do |nodename, ipaddr|
    config.vm.define nodename do |node|
      node.vm.box = "ubuntu/trusty64"
      node.vm.hostname = "#{nodename}"
      node.vm.network "private_network", ip: ipaddr
      node.vm.provider("virtualbox") { |vbox| vbox.name = "#{nodename}_#{time}" }

      # Provision
      #node.vm.provision "shell", path: "scripts/setup-all.sh"
      node.vm.provision "shell", path: "scripts/#{nodename}.sh"
    end
  end
end
